### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Esther-tec**

### CODE REVIEW

**Comment by HannahGouge** [comment]
I think you have done really well with this project. I like how you have set it out, it makes it very easy to read. I like how you added in simple annotations to the die and the testing class. I would like to see these annotations in the other classes to make it easier to understand what is happening in them. I also think that you could split the Run method in the Game class into separate methods that call one another. I don't think this is mandatory but it may make it easier to understand. Other than that I think you have done very well.

**Comment by Esther-tec** [comment]
> I think you have done really well with this project. I like how you have set it out, it makes it very easy to read. I like how you added in simple annotations to the die and the testing class. I would like to see these annotations in the other classes to make it easier to understand what is happening in them. I also think that you could split the Run method in the Game class into separate methods that call one another. I don't think this is mandatory but it may make it easier to understand. Other than that I think you have done very well.

Thank you

**Comment by HannahGouge** [comment]
I'm going to be honest yours was really hard to review as I couldn't see much that needed to be improved at all. Also don't worry about giving me a bunch to improvements I know there will be a lot after looking at yours. But ye. Well done!
________________________________

**Review by JosieWP — COMMENTED** [review]
Hello, your code looks great, it is well structured and you have demonstrated great use of object oriented principles in composing it. Your variables and objects are well named and have effectively fulfilled all the requirements of the code task. The only thing I can think to add is maybe you could find more opportunities to add comments within your game class. Nice work!

**Pull request merged**
